<Project>
  <PropertyGroup>
    <Version>0.2.4</Version>
    <MdkSourceRoot Condition="'$(MdkSourceRoot)' == ''">/home/arthur/RiderProjects/mdk2/Source/</MdkSourceRoot>
    <MdkLocalConfiguration Condition="'$(MdkLocalConfiguration)' == ''">Debug</MdkLocalConfiguration>
    <MdkLocalPlatform Condition="'$(MdkLocalPlatform)' == ''">x64</MdkLocalPlatform>
    <Mdk-IgnorePaths Condition="'$(Mdk-IgnorePaths)' == ''">**\*.debug.cs;obj\**\*</Mdk-IgnorePaths>
  </PropertyGroup>
  <ItemGroup>
    <CompilerVisibleProperty Include="Version" />
    <CompilerVisibleProperty Include="Configuration" />
    <CompilerVisibleProperty Include="ProjectDir" />
    <CompilerVisibleProperty Include="Mdk-IgnorePaths" />
    <CompilerVisibleProperty Include="LcdModCodeGeneratorSkipAppConfig" />
  </ItemGroup>
</Project>
