using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LcdMod.CodeGenerator;

[Generator]
public sealed class MarkdownXmlSnapshotSerializerTypes : IIncrementalGenerator
{
    const string SERIALIZER_TYPE_NAME = "MarkdownXmlSnapshotSerializer";
    const string MARKDOWN_NODE_METADATA_NAME = "LcdMod.Client.Markdown.MarkdownNode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var serializers = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidate(node),
                static (syntaxContext, _) => GetSerializerType(syntaxContext))
            .Where(static symbol => !ReferenceEquals(symbol, null));

        var input = context.CompilationProvider.Combine(serializers.Collect());

        context.RegisterSourceOutput(input, static (spc, source) =>
        {
            var compilation = source.Left;
            var serializerTypes = source.Right;
            if (serializerTypes.Length == 0)
                return;

            var markdownNodeType = compilation.GetTypeByMetadataName(MARKDOWN_NODE_METADATA_NAME);
            if (markdownNodeType == null)
                return;

            var knownTypes = GetKnownTypes(compilation, markdownNodeType);
            if (knownTypes.Count == 0)
                return;

            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var serializerType in serializerTypes.OfType<INamedTypeSymbol>())
            {
                var hintName = GetHintName(serializerType);
                if (!seen.Add(hintName))
                    continue;

                spc.AddSource(hintName, BuildSource(serializerType, knownTypes));
            }
        });
    }

    static bool IsCandidate(SyntaxNode node)
    {
        var classDeclaration = node as ClassDeclarationSyntax;
        return classDeclaration != null &&
               classDeclaration.Identifier.ValueText == SERIALIZER_TYPE_NAME &&
               classDeclaration.Modifiers.Any(m => m.ValueText == "partial");
    }

    static INamedTypeSymbol GetSerializerType(GeneratorSyntaxContext context)
    {
        var classDeclaration = context.Node as ClassDeclarationSyntax;
        if (ReferenceEquals(classDeclaration, null))
            return null;

        return context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
    }

    static List<INamedTypeSymbol> GetKnownTypes(Compilation compilation, INamedTypeSymbol markdownNodeType)
    {
        var result = new List<INamedTypeSymbol>();
        CollectKnownTypes(compilation.Assembly.GlobalNamespace, markdownNodeType, result);

        return result
            .GroupBy(static type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Select(static group => group.First())
            .OrderBy(static type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), StringComparer.Ordinal)
            .ToList();
    }

    static void CollectKnownTypes(
        INamespaceSymbol namespaceSymbol,
        INamedTypeSymbol markdownNodeType,
        List<INamedTypeSymbol> result)
    {
        foreach (var type in namespaceSymbol.GetTypeMembers())
            CollectKnownTypes(type, markdownNodeType, result);

        foreach (var childNamespace in namespaceSymbol.GetNamespaceMembers())
            CollectKnownTypes(childNamespace, markdownNodeType, result);
    }

    static void CollectKnownTypes(
        INamedTypeSymbol type,
        INamedTypeSymbol markdownNodeType,
        List<INamedTypeSymbol> result)
    {
        if (type.TypeKind == TypeKind.Class &&
            !type.IsAbstract &&
            type.Arity == 0 &&
            InheritsFrom(type, markdownNodeType))
        {
            result.Add(type);
        }

        foreach (var nestedType in type.GetTypeMembers())
            CollectKnownTypes(nestedType, markdownNodeType, result);
    }

    static bool InheritsFrom(INamedTypeSymbol type, INamedTypeSymbol baseType)
    {
        for (var current = type.BaseType; current != null; current = current.BaseType)
        {
            if (SymbolEqualityComparer.Default.Equals(current, baseType))
                return true;
        }

        return false;
    }

    static string BuildSource(INamedTypeSymbol serializerType, IReadOnlyList<INamedTypeSymbol> knownTypes)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");

        var namespaceName = serializerType.ContainingNamespace == null
            ? string.Empty
            : serializerType.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
        {
            builder.Append("namespace ");
            builder.Append(namespaceName);
            builder.AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("    ");
        builder.Append(GetAccessibility(serializerType));
        builder.AppendLine(" static partial class MarkdownXmlSnapshotSerializer");
        builder.AppendLine("    {");
        builder.AppendLine("        static partial void AddGeneratedKnownTypes(global::System.Collections.Generic.ICollection<global::System.Type> knownTypes)");
        builder.AppendLine("        {");

        foreach (var knownType in knownTypes)
        {
            builder.Append("            knownTypes.Add(typeof(");
            builder.Append(knownType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
            builder.AppendLine("));");
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");

        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
            builder.AppendLine("}");

        return builder.ToString();
    }

    static string GetHintName(INamedTypeSymbol serializerType)
    {
        var name = serializerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('.', '_')
            .Replace('+', '_');

        return name + ".MarkdownXmlSnapshotSerializerTypes.g.cs";
    }

    static string GetAccessibility(INamedTypeSymbol type)
    {
        switch (type.DeclaredAccessibility)
        {
            case Accessibility.Public:
                return "public";
            case Accessibility.Internal:
                return "internal";
            case Accessibility.Private:
                return "private";
            case Accessibility.Protected:
                return "protected";
            case Accessibility.ProtectedAndInternal:
                return "private protected";
            case Accessibility.ProtectedOrInternal:
                return "protected internal";
            default:
                return "internal";
        }
    }
}
