using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LcdMod.CodeGenerator;

[Generator]
public sealed class ObservableProperties : IIncrementalGenerator
{
    const string ATTRIBUTE_NAME = "LcdMod.Common.Mvvm.ObservablePropertyAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var fields = context.SyntaxProvider.ForAttributeWithMetadataName(
                ATTRIBUTE_NAME,
                static (node, _) => node is VariableDeclaratorSyntax,
                static (attributeContext, _) => attributeContext.TargetSymbol as IFieldSymbol)
            .Where(static field => field != null)
            .Collect();

        context.RegisterSourceOutput(fields, static (spc, collectedFields) =>
        {
            foreach (var group in collectedFields
                         .OfType<IFieldSymbol>()
                         .GroupBy(field => (ISymbol)field.ContainingType, SymbolEqualityComparer.Default))
            {
                var type = group.Key as INamedTypeSymbol;
                if (type == null || !IsPartial(type))
                    continue;

                var properties = group
                    .Where(IsSupportedField)
                    .Select(field => new ObservablePropertyDefinition(field, GetPropertyName(field.Name)))
                    .Where(property => !string.IsNullOrEmpty(property.PropertyName))
                    .OrderBy(property => property.PropertyName, StringComparer.Ordinal)
                    .ToArray();
                if (properties.Length == 0)
                    continue;

                spc.AddSource(GetHintName(type), BuildSource(type, properties));
            }
        });
    }

    static bool IsSupportedField(IFieldSymbol field)
    {
        return field != null && !field.IsStatic && !field.IsConst && !field.IsReadOnly;
    }

    static bool IsPartial(INamedTypeSymbol type)
    {
        foreach (var syntaxReference in type.DeclaringSyntaxReferences)
        {
            var declaration = syntaxReference.GetSyntax() as TypeDeclarationSyntax;
            if (declaration != null && declaration.Modifiers.Any(SyntaxKind.PartialKeyword))
                return true;
        }

        return false;
    }

    static string GetPropertyName(string fieldName)
    {
        if (string.IsNullOrEmpty(fieldName))
            return string.Empty;

        int start = 0;
        while (start < fieldName.Length && fieldName[start] == '_')
            start++;
        if (start >= fieldName.Length)
            return string.Empty;

        string name = fieldName.Substring(start);
        if (name.Length == 1)
            return name.ToUpperInvariant();
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    static string BuildSource(INamedTypeSymbol type, IReadOnlyList<ObservablePropertyDefinition> properties)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        if (!type.ContainingNamespace.IsGlobalNamespace)
        {
            builder.Append("namespace ");
            builder.AppendLine(type.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
        }

        builder.Append("    ");
        AppendTypeDeclaration(builder, type);
        builder.AppendLine();
        builder.AppendLine("    {");
        foreach (var property in properties)
            AppendProperty(builder, property);
        builder.AppendLine("    }");

        if (!type.ContainingNamespace.IsGlobalNamespace)
            builder.AppendLine("}");
        return builder.ToString();
    }

    static void AppendTypeDeclaration(StringBuilder builder, INamedTypeSymbol type)
    {
        if (type.DeclaredAccessibility == Accessibility.Public)
            builder.Append("public ");
        else if (type.DeclaredAccessibility == Accessibility.Internal)
            builder.Append("internal ");

        if (type.IsAbstract)
            builder.Append("abstract ");
        if (type.IsSealed)
            builder.Append("sealed ");

        builder.Append("partial class ");
        builder.Append(type.Name);
    }

    static void AppendProperty(StringBuilder builder, ObservablePropertyDefinition property)
    {
        string typeName = property.Field.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        builder.AppendLine();
        builder.Append("        public ");
        builder.Append(typeName);
        builder.Append(' ');
        builder.AppendLine(property.PropertyName);
        builder.AppendLine("        {");
        builder.Append("            get { return ");
        builder.Append(property.Field.Name);
        builder.AppendLine("; }");
        builder.Append("            set { SetObservableProperty(ref ");
        builder.Append(property.Field.Name);
        builder.Append(", value, \"");
        builder.Append(property.PropertyName);
        builder.AppendLine("\"); }");
        builder.AppendLine("        }");
    }

    static string GetHintName(INamedTypeSymbol type)
    {
        return type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
                   .Replace("global::", string.Empty)
                   .Replace(".", "_") + ".ObservableProperties.g.cs";
    }

    readonly struct ObservablePropertyDefinition
    {
        public readonly IFieldSymbol Field;
        public readonly string PropertyName;

        public ObservablePropertyDefinition(IFieldSymbol field, string propertyName)
        {
            Field = field;
            PropertyName = propertyName;
        }
    }
}
