using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LcdModCodeGenerator;

[Generator]
public class ClonableContract : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(postInitializationContext =>
            postInitializationContext.AddSource("IClonableContract.g.cs", ClonableContractInterfaceSource));

        var clonableTypes = context.SyntaxProvider
            .CreateSyntaxProvider(
                (node, _) => IsCandidate(node),
                (syntaxContext, _) => GetTargetType(syntaxContext))
            .Where(symbol => !ReferenceEquals(symbol, null));

        context.RegisterSourceOutput(
            clonableTypes.Collect(),
            (sourceProductionContext, symbols) =>
            {
                var seen = new HashSet<string>(StringComparer.Ordinal);
                foreach (var symbol in symbols.OfType<INamedTypeSymbol>())
                {
                    var hintName = GetHintName(symbol);
                    if (!seen.Add(hintName))
                        continue;

                    var source = BuildSource(symbol);
                    if (ReferenceEquals(source, null))
                        continue;

                    sourceProductionContext.AddSource(hintName, source);
                }
            });
    }

    static bool IsCandidate(SyntaxNode node)
    {
        var classDeclaration = node as ClassDeclarationSyntax;
        return classDeclaration != null && classDeclaration.BaseList != null;
    }

    static INamedTypeSymbol GetTargetType(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (ReferenceEquals(symbol, null))
            return null;

        if (!ImplementsClonableContractInterface(symbol))
            return null;

        if (!classDeclaration.Modifiers.Any(m => m.ValueText == "partial"))
            return null;

        if (HasCopyFromMethod(symbol))
            return null;

        return symbol;
    }

    static bool ImplementsClonableContractInterface(INamedTypeSymbol symbol)
    {
        foreach (var implementedInterface in symbol.AllInterfaces)
        {
            if (implementedInterface.Name != "IClonableContract")
                continue;

            if (implementedInterface.Arity == 1)
                return true;
        }

        return false;
    }

    static bool HasCopyFromMethod(INamedTypeSymbol symbol)
    {
        foreach (var method in symbol.GetMembers().OfType<IMethodSymbol>())
        {
            if (method.Name != "CopyFrom")
                continue;

            if (method.Parameters.Length != 1)
                continue;

            if (!SymbolEqualityComparer.Default.Equals(method.Parameters[0].Type, symbol))
                continue;

            return true;
        }

        return false;
    }

    static string BuildSource(INamedTypeSymbol typeSymbol)
    {
        var clonableProperties = typeSymbol.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(IsProtoMemberProperty)
            .OrderBy(GetProtoMemberOrder)
            .ToArray();

        if (clonableProperties.Length == 0)
            return null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");

        var namespaceName = typeSymbol.ContainingNamespace == null
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();
        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
        {
            builder.Append("namespace ");
            builder.Append(namespaceName);
            builder.AppendLine();
            builder.AppendLine("{");
        }

        AppendContainingTypeDeclarations(builder, typeSymbol, true);

        builder.AppendLine("        public void CopyFrom(" + typeSymbol.Name + " other)");
        builder.AppendLine("        {");
        builder.AppendLine("            if (global::System.Object.ReferenceEquals(other, null))");
        builder.AppendLine("                throw new global::System.ArgumentNullException(\"other\");");
        builder.AppendLine();

        foreach (var property in clonableProperties)
            builder.AppendLine("            " +property.Name + " = other." + property.Name + ";");

        builder.AppendLine("        }");

        AppendContainingTypeDeclarations(builder, typeSymbol, false);

        if (!string.IsNullOrEmpty(namespaceName) && namespaceName != "<global namespace>")
            builder.AppendLine("}");

        return builder.ToString();
    }

    static void AppendContainingTypeDeclarations(StringBuilder builder, INamedTypeSymbol typeSymbol, bool open)
    {
        var containingTypes = new List<INamedTypeSymbol>();
        var current = typeSymbol;
        while (!ReferenceEquals(current, null))
        {
            containingTypes.Add(current);
            current = current.ContainingType;
        }

        if (open)
        {
            containingTypes.Reverse();
            foreach (var type in containingTypes)
            {
                builder.Append("    partial class ");
                builder.Append(type.Name);
                AppendTypeParameters(builder, type);
                builder.AppendLine();
                builder.AppendLine("    {");
            }
        }
        else
        {
            foreach (var unused in containingTypes)
                builder.AppendLine("    }");
        }
    }

    static void AppendTypeParameters(StringBuilder builder, INamedTypeSymbol typeSymbol)
    {
        if (typeSymbol.TypeParameters.Length == 0)
            return;

        builder.Append("<");
        for (var i = 0; i < typeSymbol.TypeParameters.Length; i++)
        {
            if (i > 0)
                builder.Append(", ");

            builder.Append(typeSymbol.TypeParameters[i].Name);
        }

        builder.Append(">");
    }

    static bool IsProtoMemberProperty(IPropertySymbol property)
    {
        if (property.IsStatic || property.IsIndexer)
            return false;

        if (ReferenceEquals(property.SetMethod, null) || ReferenceEquals(property.GetMethod, null))
            return false;

        foreach (var attribute in property.GetAttributes())
        {
            var attributeName = attribute.AttributeClass == null ? string.Empty : attribute.AttributeClass.Name;
            if (attributeName == "ProtoMemberAttribute" || attributeName == "ProtoMember")
                return true;
        }

        return false;
    }

    static int GetProtoMemberOrder(IPropertySymbol property)
    {
        foreach (var attribute in property.GetAttributes())
        {
            var attributeName = attribute.AttributeClass == null ? string.Empty : attribute.AttributeClass.Name;
            if (attributeName != "ProtoMemberAttribute" && attributeName != "ProtoMember")
                continue;

            if (attribute.ConstructorArguments.Length == 0)
                return int.MaxValue;

            var value = attribute.ConstructorArguments[0].Value;
            if (value is int)
                return (int)value;

            return int.MaxValue;
        }

        return int.MaxValue;
    }

    static string GetHintName(INamedTypeSymbol typeSymbol)
    {
        var fullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(".", "_");

        return fullName + ".CopyFrom.g.cs";
    }

    const string ClonableContractInterfaceSource = @"// <auto-generated/>
namespace Generated
{
    public interface IClonableContract<T>
    {
        void CopyFrom(T other);
    }
}
";

}