using System;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LcdModCodeGenerator;

[Generator]
public sealed class MdkPackTestPartialGenerator : IIncrementalGenerator
{
    const string ATTRIBUTE_SOURCE = @"// <auto-generated/>
namespace Generated
{
    [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal sealed class MdkPackTestAttribute : global::System.Attribute
    {
    }
}";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var targets = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => IsCandidate(node),
                static (syntaxContext, _) => GetTarget(syntaxContext))
            .Where(static target => target != null)
            .Collect();

        context.RegisterSourceOutput(targets, static (spc, collectedTargets) =>
        {
            var targets = collectedTargets
                .OfType<Target>()
                .GroupBy(target => target.HintName)
                .Select(group => group.First())
                .ToArray();

            if (targets.Length == 0)
                return;

            spc.AddSource("MdkPackTestAttribute.g.cs", ATTRIBUTE_SOURCE);
            foreach (var target in targets)
                spc.AddSource(target.HintName + ".g.cs", BuildPartialSource(target));
        });
    }

    static bool IsCandidate(SyntaxNode node)
    {
        var classDeclaration = node as ClassDeclarationSyntax;
        if (classDeclaration == null ||
            classDeclaration.AttributeLists.Count == 0 ||
            !classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            return false;

        foreach (var attributeList in classDeclaration.AttributeLists)
        {
            foreach (var attribute in attributeList.Attributes)
            {
                if (IsMdkPackTestAttributeName(attribute.Name.ToString()))
                    return true;
            }
        }

        return false;
    }

    static Target GetTarget(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not { } symbol)
            return null;

        return new Target(
            symbol.ContainingNamespace?.IsGlobalNamespace == false ? symbol.ContainingNamespace.ToDisplayString() : string.Empty,
            GetAccessibility(symbol.DeclaredAccessibility),
            symbol.IsStatic,
            symbol.Name,
            SanitizeHintName(symbol.ToDisplayString()));
    }

    static bool IsMdkPackTestAttributeName(string name)
    {
        return name == "MdkPackTest" ||
               name == "MdkPackTestAttribute" ||
               name.EndsWith(".MdkPackTest", StringComparison.Ordinal) ||
               name.EndsWith(".MdkPackTestAttribute", StringComparison.Ordinal);
    }

    static string BuildPartialSource(Target target)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        if (!string.IsNullOrEmpty(target.NamespaceName))
        {
            builder.Append("namespace ");
            builder.Append(target.NamespaceName);
            builder.AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("    ");
        builder.Append(target.Accessibility);
        if (target.IsStatic)
            builder.Append(" static");
        builder.Append(" partial class ");
        builder.Append(target.TypeName);
        builder.AppendLine();
        builder.AppendLine("    {");
        builder.AppendLine("        public const string GeneratedByMdkPackTest = \"Generated by LcdModCodeGenerator\";");
        builder.AppendLine("    }");

        if (!string.IsNullOrEmpty(target.NamespaceName))
            builder.AppendLine("}");

        return builder.ToString();
    }

    static string GetAccessibility(Accessibility accessibility)
    {
        switch (accessibility)
        {
            case Accessibility.Public:
                return "public";
            case Accessibility.Internal:
                return "internal";
            default:
                return "internal";
        }
    }

    static string SanitizeHintName(string name)
    {
        var builder = new StringBuilder(name.Length);
        foreach (var c in name)
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        builder.Append("_MdkPackTestPartial");
        return builder.ToString();
    }

    sealed class Target
    {
        public readonly string NamespaceName;
        public readonly string Accessibility;
        public readonly bool IsStatic;
        public readonly string TypeName;
        public readonly string HintName;

        public Target(string namespaceName, string accessibility, bool isStatic, string typeName, string hintName)
        {
            NamespaceName = namespaceName;
            Accessibility = accessibility;
            IsStatic = isStatic;
            TypeName = typeName;
            HintName = hintName;
        }
    }
}
